jobs:
  CloneRepo:
    uses: git-checkout@v1
    with:
      url: https://github.com/joshua-paperspace/wandb-parallel
    outputs:
      repo:
        type: volume
    resources:
      instance-type: C4
  WandBMaster:
    uses: script@v1
    with:
      image: nvcr.io/nvidia/pytorch:21.10-py3
      script: |-
        cd /inputs/repo/
        mkdir configs
        pip install wandb -q
        python wandb_sweep_master.py
        echo ls ./configs
        ls ./configs
        cp -r ./configs /outputs
        echo ls /outputs
        ls /outputs
        echo ls /outputs/configs
        ls /outputs/configs
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    outputs:
      repo:
        type: volume
      configs:
        type: dataset
        with:
          ref: dsxbr4wc9x8ttbv
    resources:
      instance-type: C4
  WandBSweep1:
    uses: script@v1
    with:
      image: nvcr.io/nvidia/pytorch:21.10-py3
      script: |-
        cd /inputs/repo/
        echo ls /inputs
        ls /inputs
        echo ls /inputs/configs/
        ls /inputs/configs/
        echo ls /inputs/configs/data/
        ls /inputs/configs/data/
        pip install wandb -q
        python wandb_sweep.py -c config1
    needs:
      - CloneRepo
      - WandBMaster
    inputs:
      repo: CloneRepo.outputs.repo
      configs:
        type: dataset
        with:
          ref: dsxbr4wc9x8ttbv
    resources:
      instance-type: A6000
  WandBSweep2:
    uses: script@v1
    with:
      image: nvcr.io/nvidia/pytorch:21.10-py3
      script: |-
        cd /inputs/repo/
        pip install wandb -q
        python wandb_sweep.py -c config2
    needs:
      - CloneRepo
      - WandBMaster
    inputs:
      repo: CloneRepo.outputs.repo
      configs:
        type: dataset
        with:
          ref: dsxbr4wc9x8ttbv
    resources:
      instance-type: A6000
  WandBSweep3:
    uses: script@v1
    with:
      image: nvcr.io/nvidia/pytorch:21.10-py3
      script: |-
        cd /inputs/repo/
        pip install wandb -q
        python wandb_sweep.py -c config3
    needs:
      - CloneRepo
      - WandBMaster
    inputs:
      repo: CloneRepo.outputs.repo
      configs:
        type: dataset
        with:
          ref: dsxbr4wc9x8ttbv
    resources:
      instance-type: A6000